export const fallbackCategories = [
  {
    id: 'cat-1',
    name: 'Pure Honey (মধু)',
    slug: 'pure-honey',
    description: '100% natural, raw & unprocessed honey directly sourced from Sundarban and Mustard flowers.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 1,
    isActive: true,
    _count: { products: 12 },
    subcategories: [
      { id: 'sub-1', name: 'Sundarban Raw Honey', slug: 'sundarban-raw-honey', isActive: true, sortOrder: 1 },
      { id: 'sub-2', name: 'Mustard Flower Honey', slug: 'mustard-flower-honey', isActive: true, sortOrder: 2 },
      { id: 'sub-3', name: 'Litchi Flower Honey', slug: 'litchi-flower-honey', isActive: true, sortOrder: 3 },
      { id: 'sub-4', name: 'Black Seed Honey', slug: 'kalojira-honey', isActive: true, sortOrder: 4 },
    ]
  },
  {
    id: 'cat-2',
    name: 'Cold Pressed Oils (তেল)',
    slug: 'cold-pressed-oils',
    description: 'Traditional wood-pressed (Ghani-bhanga) pure edible oils for healthy cooking.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 2,
    isActive: true,
    _count: { products: 8 },
    subcategories: [
      { id: 'sub-5', name: 'Extra Virgin Mustard Oil', slug: 'mustard-oil', isActive: true, sortOrder: 1 },
      { id: 'sub-6', name: 'Cold Pressed Coconut Oil', slug: 'coconut-oil', isActive: true, sortOrder: 2 },
      { id: 'sub-7', name: 'Black Seed Oil', slug: 'kalojira-oil', isActive: true, sortOrder: 3 },
    ]
  },
  {
    id: 'cat-3',
    name: 'Organic Ghee & Dairy (ঘি)',
    slug: 'organic-ghee-dairy',
    description: 'Traditional Bilona & Grass-Fed pure cow milk ghee with aromatic granulations.',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 3,
    isActive: true,
    _count: { products: 6 },
    subcategories: [
      { id: 'sub-8', name: 'Pabna Desi Cow Ghee', slug: 'pabna-desi-cow-ghee', isActive: true, sortOrder: 1 },
      { id: 'sub-9', name: 'A2 Vedic Bilona Ghee', slug: 'a2-vedic-ghee', isActive: true, sortOrder: 2 },
    ]
  },
  {
    id: 'cat-4',
    name: 'Premium Nuts & Dates (বাদাম ও খেজুর)',
    slug: 'nuts-and-dates',
    description: 'Handpicked premium grade Medjool, Ajwa dates, and raw crunchy dry fruits.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 4,
    isActive: true,
    _count: { products: 15 },
    subcategories: [
      { id: 'sub-10', name: 'Ajwa Al-Madinah Dates', slug: 'ajwa-dates', isActive: true, sortOrder: 1 },
      { id: 'sub-11', name: 'California Almonds', slug: 'almonds', isActive: true, sortOrder: 2 },
    ]
  },
  {
    id: 'cat-5',
    name: 'Organic Spices & Herbs (মশলা)',
    slug: 'spices-and-herbs',
    description: 'Pure sun-dried stone-ground turmeric, chili, cumin, and hill-tract spices.',
    image: 'https://images.unsplash.com/photo-1596040033282-be29f79efbb9?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1596040033282-be29f79efbb9?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 5,
    isActive: true,
    _count: { products: 10 },
    subcategories: []
  },
  {
    id: 'cat-6',
    name: 'Seeds & Superfoods (সুপারফুড)',
    slug: 'seeds-and-superfoods',
    description: 'Nutrient-rich Chia seeds, Pumpkin seeds, and organic Moringa leaf powder.',
    image: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=1200&q=80',
    sortOrder: 6,
    isActive: true,
    _count: { products: 8 },
    subcategories: []
  }
]

export const fallbackBrands = [
  { id: 'br-1', name: 'Shuddho Farm Fresh', slug: 'shuddho-farm-fresh', _count: { products: 18 } },
  { id: 'br-2', name: 'Sundarban Native', slug: 'sundarban-native', _count: { products: 12 } },
  { id: 'br-3', name: 'Borno Organics', slug: 'borno-organics', _count: { products: 8 } },
  { id: 'br-4', name: 'Arabian Palms', slug: 'arabian-palms', _count: { products: 14 } },
]

export const fallbackProducts = [
  {
    id: 'prod-1',
    name: 'Raw Sundarban Wild Honey (সুন্দরবনের প্রাকৃতিক মধু)',
    slug: 'raw-sundarban-wild-honey-500g',
    sku: 'SB-HNY-001',
    categoryId: 'cat-1',
    brandId: 'br-2',
    shortDesc: '100% Raw, unfiltered honey gathered directly from Sundarban mangrove deep forests.',
    description: 'Sundarban Raw Honey is collected directly by traditional honey-hunters (Mawals) from the deep mangrove forest. Free from heating, pasteurization, or added sugars. Naturally rich in enzymes, pollen, and antioxidants.',
    thumbnail: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    regularPrice: 850,
    salePrice: 750,
    stock: 45,
    unit: '500g Glass Jar',
    isFeatured: true,
    isBestSelling: true,
    isTrending: true,
    isNewArrival: true,
    isOffer: true,
    isOrganic: true,
    isFreeDelivery: false,
    isPublished: true,
    isFlashSale: true,
    avgRating: 4.9,
    reviewCount: 38,
    soldCount: 142,
    category: { name: 'Pure Honey (মধু)', slug: 'pure-honey' },
    brand: { name: 'Sundarban Native' },
    images: [{ id: 'img-1', url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Sundarban Honey' }],
    variants: [
      { id: 'v-1', name: '500g Jar', price: 850, salePrice: 750, stock: 30, isDefault: true },
      { id: 'v-2', name: '1000g (1kg) Jar', price: 1600, salePrice: 1400, stock: 15, isDefault: false },
    ],
    attributes: [
      { id: 'att-1', name: 'Purity', value: '100% Natural Mawali Wild Harvest' },
      { id: 'att-2', name: 'Origin', value: 'Sundarbans, Bangladesh' },
    ],
    reviews: []
  },
  {
    id: 'prod-2',
    name: 'Traditional Ghani Cold-Pressed Mustard Oil (ঘানি ভাঙা সরিষার তেল)',
    slug: 'ghani-cold-pressed-mustard-oil-1l',
    sku: 'SB-OIL-001',
    categoryId: 'cat-2',
    brandId: 'br-3',
    shortDesc: 'Pure wooden-pressed pungent mustard oil from local desi mustard seeds.',
    description: 'Extracted using traditional wooden Ghani at slow speed and low temperature to retain full pungency (ঝাঁঝ), aroma, and essential fatty acids.',
    thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    regularPrice: 380,
    salePrice: 340,
    stock: 60,
    unit: '1 Litre Bottle',
    isFeatured: true,
    isBestSelling: true,
    isTrending: true,
    isNewArrival: true,
    isOffer: true,
    isOrganic: true,
    isFreeDelivery: false,
    isPublished: true,
    isFlashSale: true,
    avgRating: 4.8,
    reviewCount: 29,
    soldCount: 210,
    category: { name: 'Cold Pressed Oils (তেল)', slug: 'cold-pressed-oils' },
    brand: { name: 'Borno Organics' },
    images: [{ id: 'img-2', url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Mustard Oil' }],
    variants: [
      { id: 'v-3', name: '1 Litre Bottle', price: 380, salePrice: 340, stock: 40, isDefault: true },
      { id: 'v-4', name: '2 Litre Can', price: 740, salePrice: 650, stock: 20, isDefault: false },
    ],
    attributes: [],
    reviews: []
  },
  {
    id: 'prod-3',
    name: 'Pabna Desi Cow Pure Ghee (পাবনার খাঁটি গাওয়া ঘি)',
    slug: 'pabna-desi-cow-pure-ghee-500g',
    sku: 'SB-GHE-001',
    categoryId: 'cat-3',
    brandId: 'br-1',
    shortDesc: 'Aromatic granular butter ghee prepared from village grass-fed cow milk.',
    description: 'Traditional Pabna style pure cow milk ghee prepared through slow churning of fresh cream. Rich golden color, heavenly aroma, and authentic granular texture.',
    thumbnail: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    regularPrice: 1100,
    salePrice: 950,
    stock: 35,
    unit: '500g Jar',
    isFeatured: true,
    isBestSelling: true,
    isTrending: true,
    isNewArrival: false,
    isOffer: true,
    isOrganic: true,
    isFreeDelivery: true,
    isPublished: true,
    isFlashSale: false,
    avgRating: 5.0,
    reviewCount: 45,
    soldCount: 98,
    category: { name: 'Organic Ghee & Dairy (ঘি)', slug: 'organic-ghee-dairy' },
    brand: { name: 'Shuddho Farm Fresh' },
    images: [{ id: 'img-3', url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Desi Ghee' }],
    variants: [
      { id: 'v-5', name: '500g Jar', price: 1100, salePrice: 950, stock: 20, isDefault: true },
      { id: 'v-6', name: '1000g (1kg) Jar', price: 2100, salePrice: 1850, stock: 15, isDefault: false },
    ],
    attributes: [],
    reviews: []
  },
  {
    id: 'prod-4',
    name: 'Ajwa Dates of Al-Madinah (মদিনার প্রিমিয়াম আজওয়া খেজুর)',
    slug: 'ajwa-dates-al-madinah-500g',
    sku: 'SB-DAT-001',
    categoryId: 'cat-4',
    brandId: 'br-4',
    shortDesc: 'Authentic VIP grade soft & chewy Ajwa dates imported directly from Saudi Arabia.',
    description: 'Directly imported VIP grade Ajwa dates from Madinah Munawwarah. Naturally sweet, high in dietary fiber, iron, and potassium.',
    thumbnail: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    regularPrice: 950,
    salePrice: 820,
    stock: 50,
    unit: '500g Box',
    isFeatured: true,
    isBestSelling: true,
    isTrending: true,
    isNewArrival: false,
    isFlashSale: true,
    isOrganic: true,
    isOffer: true,
    isFreeDelivery: false,
    isPublished: true,
    avgRating: 4.9,
    reviewCount: 52,
    soldCount: 180,
    category: { name: 'Premium Nuts & Dates (বাদাম ও খেজুর)', slug: 'nuts-and-dates' },
    brand: { name: 'Arabian Palms' },
    images: [{ id: 'img-4', url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Ajwa Dates' }],
    variants: [
      { id: 'v-7', name: '500g Box', price: 950, salePrice: 820, stock: 35, isDefault: true },
      { id: 'v-8', name: '1000g (1kg) Box', price: 1800, salePrice: 1580, stock: 15, isDefault: false },
    ],
    attributes: [],
    reviews: []
  },
  {
    id: 'prod-5',
    name: 'Organic Superfood Chia Seeds (অর্গানিক চিয়া সিড)',
    slug: 'organic-superfood-chia-seeds-250g',
    sku: 'SB-SED-001',
    categoryId: 'cat-6',
    brandId: 'br-1',
    shortDesc: 'Certified organic black chia seeds rich in Omega-3, fiber, and plant protein.',
    description: 'High-purity raw organic chia seeds. Excellent source of Omega-3 fatty acids, calcium, and dietary fiber.',
    thumbnail: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80',
    regularPrice: 420,
    salePrice: 350,
    stock: 75,
    unit: '250g Pouch',
    isFeatured: true,
    isBestSelling: true,
    isTrending: true,
    isNewArrival: true,
    isFlashSale: true,
    isOrganic: true,
    isOffer: true,
    isFreeDelivery: false,
    isPublished: true,
    avgRating: 4.7,
    reviewCount: 22,
    soldCount: 88,
    category: { name: 'Seeds & Superfoods (সুপারফুড)', slug: 'seeds-and-superfoods' },
    brand: { name: 'Shuddho Farm Fresh' },
    images: [{ id: 'img-5', url: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Chia Seeds' }],
    variants: [],
    attributes: [],
    reviews: []
  },
  {
    id: 'prod-6',
    name: 'Kashmiri Organic Mongra Saffron (কাশ্মীরি জাফরান / কেশর)',
    slug: 'kashmiri-organic-mongra-saffron-1g',
    sku: 'SB-SPC-001',
    categoryId: 'cat-5',
    brandId: 'br-1',
    shortDesc: 'Grade 1 pure Kashmiri red saffron strands with intense natural aroma.',
    description: '100% Pure certified Kashmiri Mongra Saffron with full deep-red stigmata. Provides radiant golden hue and royal aroma.',
    thumbnail: 'https://images.unsplash.com/photo-1596040033282-be29f79efbb9?auto=format&fit=crop&w=600&q=80',
    regularPrice: 450,
    salePrice: 390,
    stock: 30,
    unit: '1 Gram Acrylic Box',
    isFeatured: true,
    isBestSelling: false,
    isTrending: true,
    isNewArrival: true,
    isOffer: true,
    isOrganic: true,
    isFreeDelivery: true,
    isPublished: true,
    isFlashSale: false,
    avgRating: 5.0,
    reviewCount: 16,
    soldCount: 42,
    category: { name: 'Organic Spices & Herbs (মশলা)', slug: 'spices-and-herbs' },
    brand: { name: 'Shuddho Farm Fresh' },
    images: [{ id: 'img-6', url: 'https://images.unsplash.com/photo-1596040033282-be29f79efbb9?auto=format&fit=crop&w=600&q=80', sortOrder: 0, alt: 'Saffron' }],
    variants: [],
    attributes: [],
    reviews: []
  }
]

export const fallbackBanners = [
  {
    id: 'ban-1',
    title: '100% Pure Organic Living',
    heading: 'Pure & Natural Grocery Directly From Farmers',
    subheading: 'Enjoy genuine taste, zero chemicals & guaranteed freshness across Bangladesh.',
    buttonText: 'Shop Organic Now',
    buttonUrl: '/shop',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1600&q=80',
    type: 'HERO',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'ban-2',
    title: 'Sundarban Raw Wild Honey',
    heading: 'Harvested Directly From Deep Mangroves',
    subheading: 'Lab tested pure honey with natural enzymes, vitamins & immune support.',
    buttonText: 'Order Honey',
    buttonUrl: '/shop?category=pure-honey',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=1600&q=80',
    type: 'HERO',
    sortOrder: 2,
    isActive: true,
  }
]

export const fallbackSections = [
  { id: 'sec-1', type: 'HERO_SLIDER', heading: 'Pure & Organic', subheading: 'From Farm to Your Table', sortOrder: 1, isActive: true, showOnMobile: true, showOnDesktop: true, productCount: 0 },
  { id: 'sec-2', type: 'FEATURED_CATEGORIES', heading: 'Shop by Category', subheading: 'Explore our wide range of organic products', sortOrder: 2, isActive: true, showOnMobile: true, showOnDesktop: true, productCount: 8 },
  { id: 'sec-3', type: 'FLASH_SALE', heading: 'Flash Sale 🔥', subheading: 'Limited time offers — grab before it\'s gone!', sortOrder: 3, isActive: true, showOnMobile: true, showOnDesktop: true, productCount: 6 },
  { id: 'sec-4', type: 'TOP_SELLERS', heading: 'Top Selling Products', subheading: 'Products our customers love the most', sortOrder: 4, isActive: true, productSource: 'BEST_SELLING', showOnMobile: true, showOnDesktop: true, productCount: 8 },
  { id: 'sec-5', type: 'NEW_ARRIVALS', heading: 'New Arrivals', subheading: 'Just landed — fresh stock for you', sortOrder: 5, isActive: true, productSource: 'NEW_ARRIVAL', showOnMobile: true, showOnDesktop: true, productCount: 8 },
  { id: 'sec-6', type: 'COMBO_DEALS', heading: 'Combo Deals', subheading: 'Save more with our value bundles', sortOrder: 6, isActive: true, showOnMobile: true, showOnDesktop: true, productCount: 4 },
  { id: 'sec-7', type: 'ORGANIC', heading: '100% Certified Organic', subheading: 'Pure natural wellness for your whole family', sortOrder: 7, isActive: true, productSource: 'FEATURED', showOnMobile: true, showOnDesktop: true, productCount: 8 },
]

export const fallbackDeliveryZones = [
  {
    id: 'zone-dhaka',
    name: 'Dhaka',
    description: 'Dhaka Metropolitan Area',
    isActive: true,
    rates: [
      { id: 'rate-1', name: 'Inside Dhaka City', charge: 60, freeThreshold: 999, estimatedDays: '1-2 days', isActive: true },
      { id: 'rate-2', name: 'Dhaka Outskirts', charge: 100, freeThreshold: 1499, estimatedDays: '2-3 days', isActive: true },
    ]
  },
  {
    id: 'zone-outside-dhaka',
    name: 'Outside Dhaka',
    description: 'All other divisions',
    isActive: true,
    rates: [
      { id: 'rate-3', name: 'Outside Dhaka / All Districts', charge: 130, freeThreshold: 1999, estimatedDays: '3-5 days', isActive: true },
    ]
  }
]
